### PR TITLE
Sklearn modelling

### LINKED ISSUE #29: Develop a ML model using scikit-learn
https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3-Task3.ipynb

Upload this notebook to your jupyterHub (TLJH in your EC2) from your previous milestone and follow instruction given there. https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3-Task3.ipynb

### PR DESCRIPTION
**Pull request by dbandrews**
Closes #29

### CODE REVIEW

**Review by elabandari — APPROVED** [review]
Hi @dbandrews,

I just finished reviewing the task 3 notebook and it looks great! Unfortunately, I have no comments or suggestion.  

The milestone does mention that we have to upload the `model.joblib` to s3 and I was wondering if you had already done so? Would this be Kaicheng's S3 ?

**Comment by dbandrews** [comment]
Hey Ela - Thanks! I did not get a chance to upload 'model.joblib' yet, I'll get that in this morning. Thanks for the reminder

**Comment by dbandrews** [comment]
@elabandari I've uploaded to Kaicheng's bucket and included the screenshot for submission now. This should be buttoned up pretty well

**Review by Andrew-Tan — APPROVED** [review]
LGTM

**Pull request merged**
