### PR TITLE
Add EMR screenshot, clean up folders

### LINKED ISSUE #27: Setup your EMR cluster
- [ ] add screenshot 

https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/Milestone3.ipynb

Follow the instructions shown during the lecture to set up your EC2 instance. Please make sure you follow the below instructions.

1.1) Go to advanced options.

1.2) Choose Release 6.2.0.

1.3) Check JupyterHub 1.1.0 & Spark 3.0.1.

1.4) Core instances to be 0, master 1.

1.5) Root device EBS volume size 30 GB.

1.6) Cluster name :

1.7) Uncheck Termination protection.

1.6) Add tag, enter "Owner" under the Key field. In the Value field in the Name row, give your

1.9) Select your keypair what you have used in your previous milestone (milestone 2).

1.10) EC2 security group go with the default. Remember this is a managed service, what we learned from the shared responsibility model, and hence AWS will take care of many things. EMR comes in the list of container services.

1.11) Wait for the cluster to start. This takes around ~15 min. Wait for your cluster status to be Waiting .

Please attach this screen shots from your group for grading¶
https://github.ubc.ca/MDS-2020-21/DSCI_525_web-cloud-comp_students/blob/master/Milestones/milestone3/images/Task1.png

### PR DESCRIPTION
**Pull request by dbandrews**
Closes #27 

Add EMR setup screenshot - cleaned images into folder structure by milestone.

### CODE REVIEW

**Comment by Andrew-Tan** [comment]
milestone 2 has not yet been graded, I'm concerned about this change... how do you folks think?

**Comment by elabandari** [comment]
@Andrew-Tan Thanks for raising that point, we can leave a comment on the canvas submission maybe that signals this change?

**Comment by dbandrews** [comment]
Hey @Andrew-Tan @elabandari, good question. I actually pasted as embedded image into our milestone 2 notebook so it can render without those images in the exact folder structure.

I think we should be good to change the folders but let me know if you see any other issue with this

**Comment by elabandari** [comment]
@dbandrews, shouldn't be a problem then!

**Review by elabandari — APPROVED** [review]

**Comment by Andrew-Tan** [comment]
Yep. Seems like they've just reviewed milestone 2 and provided feedbacks.

**Review by Andrew-Tan — APPROVED** [review]
LGTM

**Pull request merged**
